export { Alfred } from './alfred.js';
export { MessagePipeline } from './message-pipeline.js';
export type { ProgressCallback, PipelineOptions } from './message-pipeline.js';
export { ConversationManager } from './conversation-manager.js';
export { ReminderScheduler } from './reminder-scheduler.js';
export { SpeechTranscriber } from './speech-transcriber.js';
export { ResponseFormatter } from './response-formatter.js';
export type { FormattedResponse } from './response-formatter.js';
export { EmbeddingService } from './embedding-service.js';
export { BackgroundTaskRunner } from './background-task-runner.js';
export { ProactiveScheduler } from './proactive-scheduler.js';
export { DocumentProcessor } from './document-processor.js';
export { ActiveLearningService } from './active-learning/active-learning-service.js';
export type { ActiveLearningOptions } from './active-learning/active-learning-service.js';
export { MemoryRetriever } from './active-learning/memory-retriever.js';
export type { RetrievedMemory } from './active-learning/memory-retriever.js';
export { MemoryExtractor } from './active-learning/memory-extractor.js';
export { MemoryConsolidator } from './active-learning/memory-consolidator.js';
export { scanSignal } from './active-learning/signal-scanner.js';
export type { SignalResult } from './active-learning/signal-scanner.js';
